pwcon <- read.csv("household_power_consumption.txt", sep=";", na.strings='?', colClasses=c('factor', 'character', 'numeric', 'numeric','numeric','numeric','numeric','numeric','numeric'))
pwcon <- transform(pwcon, Date = as.Date(Date, format="%d/%m/%Y"))
subcon <- subset(pwcon, Date >= "2007-02-01" & Date <= "2007-02-02")
datetime <- paste(subcon$Date, subcon$Time)
datetime <- strptime(datetime, format = "%Y-%m-%d %H:%M:%S")
png("plot2.png",  width = 480, height = 480, units = "px")
plot(datetime, subcon$Global_active_power, type='l', xlab = "", ylab="Global Active Power")
dev.off()
