pwcon <- read.csv("household_power_consumption.txt", sep=";", na.strings='?', colClasses=c('factor', 'character', 'numeric', 'numeric','numeric','numeric','numeric','numeric','numeric'))
pwcon <- transform(pwcon, Date = as.Date(Date, format="%d/%m/%Y"))
subcon <- subset(pwcon, Date >= "2007-02-01" & Date <= "2007-02-02")
png("plot1.png",  width = 480, height = 480, units = "px")
hist(subcon$Global_active_power, col='red', xlab=("Global Active Power (kilowatts)"), main="Global Active Power")
dev.off()
