pwcon <- read.csv("household_power_consumption.txt", sep=";", na.strings='?', colClasses=c('factor', 'character', 'numeric', 'numeric','numeric','numeric','numeric','numeric','numeric'))
pwcon <- transform(pwcon, Date = as.Date(Date, format="%d/%m/%Y"))
subcon <- subset(pwcon, Date >= "2007-02-01" & Date <= "2007-02-02")
datetime <- paste(subcon$Date, subcon$Time)
datetime <- strptime(datetime, format = "%Y-%m-%d %H:%M:%S")
png("plot4.png",  width = 480, height = 480, units = "px")
par(mfrow = c(2, 2))
with(subcon, {
  plot(datetime, Global_active_power, type='l', xlab = "", ylab="Global Active Power")
  plot(datetime, Voltage, type='l')
  plot(datetime, Sub_metering_1, type='l', xlab = '', ylab = "Energy sub metering")
  lines(datetime, Sub_metering_2, col = "red")
  lines(datetime, Sub_metering_3, col = "blue")
  plot(datetime, Global_reactive_power, type='l')
})
dev.off()